
const nombres = [
  "ABRANTES CECILIA",
  "BOUZADA HERMINA MAGDALENA",
  "BRAVO VIRGINIA",
  "BUSTAMANTE ROCIO SOLEDAD",
  "CRUZ FLORENCIA",
  "FERNANDEZ MARIANA",
  "GUGLIELMINO MARIA BELEN",
  "GUTIERREZ VANESA",
  "HERNANDEZ YESICA GISELA",
  "LAMURA CAMILA ABIGAIL",
  "MORALES MARCELA",
  "PRIETO VANESA",
  "RAMOS CANDELA",
  "RIZZO PONZANO VANESA",
  "ROLDAN DAIANA",
  "RUIZ MARIA EUGENIA",
  "SARMIENTO GABRIELA",
  "VILLODAS MARCELA VERONICA",
  "ALTAMIRANO MARIA JOSE",
  "ANGEL ELENA",
  "BRIOZZO LAURA",
  "CRIVELLI MARIA LAURA",
  "DE LA IGLESIA MARIA LAURA",
  "DERCKAZ MARIA SOLEDAD",
  "DIAZ RITA MARIA",
  "DUMAS VIRGINIA",
  "FABBRI BETHANCOURT MARIA FLORENCIA",
  "FERNANDEZ MARTINEZ CAROLINA",
  "FERRANTE CHRISTIAN LUIS",
  "GONZALEZ JENNIFER MARIA",
  "GRIOLLI ANDREA",
  "IBARRA VIVIANA",
  "IRIGOYEN MARIA BELEN",
  "MADERO AGUSTINA",
  "MANTELLI MIRTA NOEMI",
  "OJEDA MARIA SOLEDAD",
  "PEREZ ALICIA BELEN",
  "PEREZ JORGELINA",
  "PETRONI VANINA",
  "POLEDO GEORGINA",
  "POWELL CAMILA",
  "QUINTANA ROMINA ELISABETH",
  "ROMANO PINTOS DEBORA GISELE",
  "SALZANO MARIA DEL PILAR",
  "SERRANO BENITEZ DANIELA FERNANDA",
  "TORRES ALEJANDRA ELIZABETH",
  "VALDEZ MAILEN LUCILA",
  "VAZQUEZ DAMARIS SOLANGE",
  "VAZQUEZ LUZ",
  "VELASCO ANALIA VERONICA",
  "WEBER ROCIO SOLEDAD",
  "AMOROSO SOFIA",
  "ARGUELLO RITA JIMENA",
  "ARZAMENDIA MEDINA ROSA NATHALI",
  "BONALDO MARIA PAULA",
  "BUFFAGNA MARIA CARLA",
  "BUSTAMANTE BEATRIZ ELIZABET",
  "DURANTE FEREICO",
  "ETCHEMAITE ANA",
  "GUIOT MARIA VICTORIA",
  "LASPOUMADERES FERNANDEZ",
  "LEON MICAELA",
  "LOPEZ NANCY BEATRIZ",
  "LOVRENCO VERONICA",
  "MARIANI DIEGO",
  "NATALE JUAN CRUZ",
  "NAUGHTON MARIELA",
  "PAZOS MARIANO",
  "POZO MARIA CECILIA",
  "RAU CARMEN MARIELA",
  "RIOS MARIA EUGENIA",
  "RODRIGUEZ JOSE",
  "ROMERO LUIS ALBERTO",
  "RUSSO MARCELO ADRIAN",
  "SANTA MARIA ASTRID VANINA",
  "SERRA LAURA CECILIA",
  "STORK GRACIELA",
  "TAMAME ANA",
  "VON DER WALL CECILIA"
];

  const horarios = [
    "08:00", "08:30",
    "09:00", "09:30",
    "10:00", "10:30",
    "11:00", "11:30",
     "12:30",
    "13:00", "13:30",
    "14:00", "14:30",
    "15:00", "15:30",
    "16:00", "16:30"
  ];

  const startModels = async (conn, user,horario) => {
    console.log("llega acá")
    try {
      // Sincroniza el modelo con la base de datos (crea la tabla si no existe)
      await conn.sync({ force: true });
      
      // Utiliza bulkCreate para insertar registros en la tabla
      await user.bulkCreate(
        nombres.map(nombre => ({ name: nombre })),
      );
      await horario.bulkCreate(
        horarios.map(hora => ({ hora,data:[] })),
      );
        
      console.log('Registros creados con éxito');
    } catch (error) {
      console.error('Error al crear registros:', error);
    }
  };
  

  module.exports = startModels;